#include <iostream>
#include<windows.h>
#define color SetConsoleTextAttribute

using namespace std;

int main(){
    SetConsoleOutputCP (CP_UTF8);
    HANDLE hConsole = GetStdHandle(STD_OUTPUT_HANDLE);
    int opc;

    //SetConsoleTextAttribute (hConsole, 1);  //1 = azúl
    //SetConsoleTextAttribute (hConsole, 2);  //2 = verde
    //SetConsoleTextAttribute (hConsole, 3);  //3 = celeste
    //SetConsoleTextAttribute (hConsole, 4);  //4 = rojo
    //SetConsoleTextAttribute (hConsole, 5);  //5 = morado
    //SetConsoleTextAttribute (hConsole, 7);  //7 = blanco

    color (hConsole, 4);
    cout << "  ////////////     ////////////   ////////////       /////////   ///       ///        ///     ///  ///   /////////       ////////////"<<endl;
    cout << "///                    ///       ///        ///   ///      ///    ///   ///          ///  ///     ///   ///       ///  ///   "<<endl;
    cout << "  ////////////        ///       ////////////     ///      ///       ///             /////        ///   ///       ///    //////////// "<<endl;
    cout << "            ///      ///       ///   ///        ////////////       ///             ///  ///     ///   ///       ///               /// "<<endl;
    cout << "////////////        ///       ///       ///    ///      ///       ///             ///     ///  ///   //////////       //////////// "<<endl;

        do{
        color (hConsole, 132);
        cout<<"\n***********ÁLBUMES**************"<<endl;
        color (hConsole, 7);
        cout<<"1.......................Mixtape"<<endl;
        cout<<"2.......................I am NOT"<<endl;
        cout<<"3.......................I am WHO"<<endl;
        cout<<"4.......................I am YOU"<<endl;
        cout<<"5.......................Clé 1: MIROH"<<endl;
        cout<<"6.......................Clé 2: Yellow Wood"<<endl;
        cout<<"7.......................Clé: Levanter"<<endl;
        cout<<"8.......................SKZ2020"<<endl;
        cout<<"9.......................GO LIVE"<<endl;
        cout<<"10......................IN LIFE"<<endl;
        cout<<"11......................ALL IN"<<endl;
        cout<<"12......................NOEASY"<<endl;
        cout<<"13......................Christmas EveL"<<endl;
        cout<<"14......................SKZ2021"<<endl;
        cout<<"15......................ODDINARY"<<endl;
        cout<<"16......................CIRCUS"<<endl;
        cout<<"17......................MAXIDENT"<<endl;
        cout<<"18......................SKZ-REPLAY"<<endl;
        cout<<"19......................THE SOUND"<<endl;
        cout<<"20......................5-STAR"<<endl;
        cout<<"21......................ROCK-STAR"<<endl;
        cout<<"22......................ATE"<<endl;
        cout<<"0.......................SALIR"<<endl;
        cout<<"Ingrese una opción: ";
        cin>>opc;

        switch (opc){
        case 1: system ("cls");
        color (hConsole, 112);
        cout<<"\n***********Mixtape**************"<<endl;
        color (hConsole, 7);
        cout<<"Lanzamiento: 8 de enero de 2018"<<endl;
        cout<<"Discográfica: JYP Entertainment"<<endl;
        cout<<"Número de Canciones: 7"<<endl;
        cout<<"Canción Principal: Hellevator"<<endl;
        cout<<"Idioma: Coreano"<<endl;
        break;
        case 2:system ("cls");
        color (hConsole, 112);
        cout<<"\n***********I am NOT**************"<<endl;
        color (hConsole, 7);
        cout<<"Lanzamiento: 26 de marzo de 2018"<<endl;
        cout<<"Discográfica: JYP Entertainment"<<endl;
        cout<<"Número de Canciones: 8"<<endl;
        cout<<"Canción Principal: Distric 9"<<endl;
        cout<<"Idioma: Coreano"<<endl;
        break;
        case 3:system ("cls");
        color (hConsole, 112);
        cout<<"\n***********I am WHO**************"<<endl;
        color (hConsole, 7);
        cout<<"Lanzamiento: 6 de agosto de 2018"<<endl;
        cout<<"Discográfica: JYP Entertainment"<<endl;
        cout<<"Número de Canciones: 8"<<endl;
        cout<<"Canción Principal: My Pace"<<endl;
        cout<<"Idioma: Coreano"<<endl;
        break;
        case 4: system ("cls");
        color (hConsole, 112);
        cout<<"\n***********I am YOU**************"<<endl;
        color (hConsole, 7);
        cout<<"Lanzamiento: 22 de octubre de 2018"<<endl;
        cout<<"Discográfica: JYP Entertainment"<<endl;
        cout<<"Número de Canciones: 8"<<endl;
        cout<<"Canción Principal: I am YOU"<<endl;
        cout<<"Idioma: Coreano"<<endl;
        break;
        case 5: system ("cls");
        color (hConsole, 112);
        cout<<"\n***********Clé 1: MIROH**************"<<endl;
        color (hConsole, 7);
        cout<<"Lanzamiento: 25 de marzo de 2019"<<endl;
        cout<<"Discográfica: JYP Entertainment"<<endl;
        cout<<"Número de Canciones: 7"<<endl;
        cout<<"Canción Principal: MIROH"<<endl;
        cout<<"Idioma: Coreano"<<endl;
        break;
        case 6: system ("cls");
        color (hConsole, 112);
        cout<<"\n***********Clé 2: Yellow Wood**************"<<endl;
        color (hConsole, 7);
        cout<<"Lanzamiento: 19 de junio de 2019"<<endl;
        cout<<"Discográfica: JYP Entertainment"<<endl;
        cout<<"Número de Canciones: 7"<<endl;
        cout<<"Canción Principal: Side Effects"<<endl;
        cout<<"Idioma: Coreano"<<endl;
        break;
        case 7: system ("cls");
        color (hConsole, 112);
        cout<<"\n***********Clé: Levanter**************"<<endl;
        color (hConsole, 7);
        cout<<"Lanzamiento: 9 de diciembre de 2019"<<endl;
        cout<<"Discográfica: JYP Entertainment"<<endl;
        cout<<"Número de Canciones: 6"<<endl;
        cout<<"Canción Principal: Levanter"<<endl;
        cout<<"Idioma: Coreano"<<endl;
        break;
        case 8: system ("cls");
        color (hConsole, 112);
        cout<<"\n***********SKZ2020**************"<<endl;
        color (hConsole, 7);
        cout<<"Lanzamiento: 1 de diciembre de 2020"<<endl;
        cout<<"Discográfica: JYP Entertainment"<<endl;
        cout<<"Número de Canciones: 8"<<endl;
        cout<<"Canción Principal: ALL IN (Korean ver.)"<<endl;
        cout<<"Idioma: Coreano"<<endl;
        break;
        case 9: system ("cls");
        color (hConsole, 112);
        cout<<"\n***********GO LIVE**************"<<endl;
        color (hConsole, 7);
        cout<<"Lanzamiento: 17 de junio de 2020"<<endl;
        cout<<"Discográfica: JYP Entertainment"<<endl;
        cout<<"Número de Canciones: 14 (edición estándar)"<<endl;
        cout<<"Canción Principal: God's Menu"<<endl;
        cout<<"Idioma: Coreano"<<endl;
        break;
        case 10: system ("cls");
        color (hConsole, 112);
        cout<<"\n***********IN LIFE**************"<<endl;
        color (hConsole, 7);
        cout<<"Lanzamiento: 14 de septiembre de 2020"<<endl;
        cout<<"Discográfica: JYP Entertainment"<<endl;
        cout<<"Número de Canciones: 17 (edición deluxe)"<<endl;
        cout<<"Canción Principal: Back Door"<<endl;
        cout<<"Idioma: Coreano"<<endl;
        break;
        case 11: system ("cls");
        color (hConsole, 112);
        cout<<"\n***********ALL IN**************"<<endl;
        color (hConsole, 7);
        cout<<"Lanzamiento: 25 de noviembre de 2020"<<endl;
        cout<<"Discográfica: JYP Entertainment"<<endl;
        cout<<"Número de Canciones: 8"<<endl;
        cout<<"Canción Principal: ALL IN"<<endl;
        cout<<"Idioma: Japonés"<<endl;
        break; 
        case 12:system ("cls");
        color (hConsole, 112);
        cout<<"\n***********NOEASY**************"<<endl;
        color (hConsole, 7);
        cout<<"Lanzamiento: 23 de agosto de 2021"<<endl;
        cout<<"Discográfica: JYP Entertainment"<<endl;
        cout<<"Número de Canciones: 14"<<endl;
        cout<<"Canción Principal: Thunderous"<<endl;
        cout<<"Idioma: Coreano"<<endl;
        break; 
        case 13:system ("cls");
        color (hConsole, 112);
        cout<<"\n***********Christmas EveL**************"<<endl;
        color (hConsole, 7);
        cout<<"Lanzamiento: 28 de noviembre de 2021"<<endl;
        cout<<"Discográfica: JYP Entertainment"<<endl;
        cout<<"Número de Canciones: 4"<<endl;
        cout<<"Canción Principal: "<<endl;
        cout<<"Idioma: Coreano"<<endl;
        break;
        case 14: system ("cls");
        color (hConsole, 112);
        cout<<"\n***********SKZ2021**************"<<endl;
        color (hConsole, 7);
        cout<<"Lanzamiento: 23 de diciembre de 2021"<<endl;
        cout<<"Discográfica: JYP Entertainment"<<endl;
        cout<<"Número de Canciones: 14"<<endl;
        cout<<"Canción Principal: Scars (Korean ver.)"<<endl;
        cout<<"Idioma: Coreano"<<endl;
        break;
        case 15: system ("cls");
        color (hConsole, 112);
        cout<<"\n***********ODDINARY**************"<<endl;
        color (hConsole, 7);
        cout<<"Lanzamiento: 19 de marzo del 2022"<<endl;
        cout<<"Discográfica: JYP Entertainment"<<endl;
        cout<<"Número de Canciones: 7"<<endl;
        cout<<"Canción Principal: Maniac"<<endl;
        cout<<"Idioma: Coreano"<<endl;
        break;
        case 16: system ("cls");
        color (hConsole, 112);
        cout<<"\n***********CIRCUS**************"<<endl;
        color (hConsole, 7);
        cout<<"Lanzamiento: 21 de junio de 2022"<<endl;
        cout<<"Discográfica: JYP Entertainment"<<endl;
        cout<<"Número de Canciones: 6"<<endl;
        cout<<"Canción Principal: Circus"<<endl;
        cout<<"Idioma: Japonés"<<endl;
        break;
        case 17: system ("cls");
        color (hConsole, 112);
        cout<<"\n***********MAXIDENT**************"<<endl;
        color (hConsole, 7);
        cout<<"Lanzamiento: 7 de octubre de 2022"<<endl;
        cout<<"Discográfica: JYP Entertainment"<<endl;
        cout<<"Número de Canciones: 8"<<endl;
        cout<<"Canción Principal: Case-143"<<endl;
        cout<<"Idioma: Coreano"<<endl;
        break;
        case 18: system ("cls");
        color (hConsole, 112);
        cout<<"\n***********SKZ-REPLAY**************"<<endl;
        color (hConsole, 7);
        cout<<"Lanzamiento: 21 de diciembre de 2022"<<endl;
        cout<<"Discográfica: JYP Entertainment"<<endl;
        cout<<"Número de Canciones: 25"<<endl;
        cout<<"Canción Principal: FAM (Korean ver.)"<<endl;
        cout<<"Idioma: Coreano"<<endl;
        break;
        case 19: system ("cls");
        color (hConsole, 112);
        cout<<"\n***********THE SOUND**************"<<endl;
        color (hConsole, 7);
        cout<<"Lanzamiento: 22 de febrero de 2023"<<endl;
        cout<<"Discográfica: JYP Entertainment"<<endl;
        cout<<"Número de Canciones: 10"<<endl;
        cout<<"Canción Principal: THE SOUND"<<endl;
        cout<<"Idioma: japonés"<<endl;
        break;
        case 20: system ("cls");
        color (hConsole, 112);
        cout<<"\n***********5-STAR**************"<<endl;
        color (hConsole, 7);
        cout<<"Lanzamiento: 2 de junio de 2023"<<endl;
        cout<<"Discográfica: JYP Entertainment"<<endl;
        cout<<"Número de Canciones: 12"<<endl;
        cout<<"Canción Principal: S-class"<<endl;
        cout<<"Idioma: Coreano"<<endl;
        break;
        case 21: system ("cls");
        color (hConsole, 112);
        cout<<"\n***********ROCK-STAR**************"<<endl;
        color (hConsole, 7);
        cout<<"Lanzamiento: 10 de noviembre de 2023"<<endl;
        cout<<"Discográfica: JYP Entertainment"<<endl;
        cout<<"Número de Canciones: 8"<<endl;
        cout<<"Canción Principal: LALALALA"<<endl;
        cout<<"Idioma: Coreano"<<endl;
        break;
        case 22: system ("cls");
        color (hConsole, 112);
        cout<<"\n***********ATE**************"<<endl;
        color (hConsole, 7);
        cout<<"Lanzamiento: 19 de Julio de 2024"<<endl;
        cout<<"Discográfica: JYP Entertainment"<<endl;
        cout<<"Número de Canciones: 8"<<endl;
        cout<<"Canción Principal: CHCK CHCK BOOM"<<endl;
        cout<<"Idioma: Coreano"<<endl;
        break;
        case 0:
        color (hConsole, 3);
        cout << "\n  ////////////     ////////////   ////////////       /////////   ///       ///        ///     ///  ///   /////////       ////////////"<<endl;
        cout << "///                    ///       ///        ///   ///      ///    ///   ///          ///  ///     ///   ///       ///  ///   "<<endl;
        cout << "  ////////////        ///       ////////////     ///      ///       ///             /////        ///   ///       ///    //////////// "<<endl;
        cout << "            ///      ///       ///   ///        ////////////       ///             ///  ///     ///   ///       ///               /// "<<endl;
        cout << "////////////        ///       ///       ///    ///      ///       ///             ///     ///  ///   //////////       //////////// "<<endl;
        color (hConsole, 2);
        cout<<"\nHa salido exitosamente del programa."<<endl;
        break;
        default: system ("cls");
        color (hConsole, 4);
        cout<<"\nLa opción ingresada no es correcta. Intente de nuevo."<<endl;
            break;
        }
        }while(opc!=0);
    
    color (hConsole, 7);
    return 0;
}